# Generated by Django 4.2 on 2025-03-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_acess',
            new_name='last_access',
        ),
    ]
