# Generated by Django 4.2 on 2025-03-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='deletedAt',
            new_name='deleted_at',
        ),
    ]
