# Generated by Django 4.2 on 2025-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_createdat_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_code',
            field=models.CharField(choices=[('FILE', 'FILE'), ('AUDIO', 'AUDIO')], max_length=10, null=True),
        ),
    ]
