# Generated by Django 4.2 on 2025-03-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='size',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='extension',
            field=models.CharField(max_length=15),
        ),
    ]
